// Copyright 2025 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// AccountAllBalancesResponse An AccountAllBalancesResponse is returned on the /account/all_balances
// endpoint. It contains balances for the main account and all associated sub-accounts, along with
// their respective sub-account identifiers and balance types.
type AccountAllBalancesResponse struct {
	BlockIdentifier *BlockIdentifier `json:"block_identifier"`
	// Array of account balances including main account and all sub-accounts.
	// Each balance includes the sub-account identifier and balance type information.
	AccountBalances []*AccountBalanceWithSubAccount `json:"account_balances"`
	// Account-based blockchains that utilize a nonce or sequence number should include that number
	// in the metadata. This number could be unique to the identifier or global across the account
	// address.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// AccountBalanceWithSubAccount Represents a balance for a specific account or sub-account,
// including the sub-account identifier and balance type information.
type AccountBalanceWithSubAccount struct {
	// Sub-account identifier. Will be nil for the main account balance.
	SubAccountIdentifier *SubAccountIdentifier `json:"sub_account_identifier,omitempty"`
	// A single account/sub-account may have a balance in multiple currencies.
	Balances []*Amount `json:"balances"`
	// The type of balance (e.g., spendable, delegated, pending_undelegation, etc.)
	BalanceType string `json:"balance_type,omitempty"`
	// Sub-account specific metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}