// Copyright 2025 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// AccountBalanceWithSubAccount Represents a balance for a specific account or sub-account,
// including balance type information and metadata.
type AccountBalanceWithSubAccount struct {
	// A single account/sub-account may have a balance in multiple currencies.
	Balances []*Amount `json:"balances"`
	// The type of balance (e.g., spendable, delegated, pending_undelegation, etc.)
	BalanceType *string `json:"balance_type,omitempty"`
	// Sub-account specific metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
