// Copyright 2025 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// AllAccountBalancesResponse An AllAccountBalancesResponse is returned on the /account/all-balances
// endpoint. It contains balances for the main account and all associated sub-accounts, along with
// their respective sub-account identifiers and balance types. This response provides all account
// balances in a single request, eliminating the need for multiple calls to /account/balance with
// different sub-account identifiers.
type AllAccountBalancesResponse struct {
	BlockIdentifier *BlockIdentifier `json:"block_identifier"`
	// Array of account balances including main account and all sub-accounts. Each balance includes
	// balance type information and metadata.
	AccountBalances []*AccountBalanceWithSubAccount `json:"account_balances"`
}
