// Copyright 2026 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

import "encoding/json"

// Allow Allow specifies supported Operation status, Operation types, and all possible error
// statuses. This Allow object is used by clients to validate the correctness of a Rosetta Server
// implementation. It is expected that these clients will error if they receive some response that
// contains any of the above information that is not specified here.
type Allow struct {
	// All Operation.Status this implementation supports. Any status that is returned during parsing
	// that is not listed here will cause client validation to error.
	OperationStatuses []*OperationStatus `json:"operation_statuses"`
	// All Operation.Type this implementation supports. Any type that is returned during parsing
	// that is not listed here will cause client validation to error.
	OperationTypes []string `json:"operation_types"`
	// All Errors that this implementation could return. Any error that is returned during parsing
	// that is not listed here will cause client validation to error.
	Errors []*Error `json:"errors"`
	// Any Rosetta implementation that supports querying the balance of an account at any height in
	// the past should set this to true.
	HistoricalBalanceLookup bool `json:"historical_balance_lookup"`
	// If populated, `timestamp_start_index` indicates the first block index where block timestamps
	// are consistent. This is useful for networks that have had timestamp issues in the past.
	TimestampStartIndex *int64 `json:"timestamp_start_index,omitempty"`
	// All Call.Method this implementation supports. Any method that is returned during parsing
	// that is not listed here will cause client validation to error.
	CallMethods []string `json:"call_methods,omitempty"`
	// BalanceExemptions is an array of BalanceExemption indicating which
	// SubAccountIdentifiers may not have a balance populated. This is useful
	// for networks like Bitcoin where some UTXOs may not be spendable.
	BalanceExemptions []*BalanceExemption `json:"balance_exemptions,omitempty"`
	// MempoolCoins is a boolean indicating if the implementation supports
	// returning unconfirmed coins from the mempool. If this is true, the
	// implementation should return mempool coins in the /account/coins
	// response.
	MempoolCoins bool `json:"mempool_coins,omitempty"`
	// BlockHashSignature indicates whether the implementation supports
	// signing the block hash. If this is true, the implementation should
	// support signing the block hash in the /construction/payloads
	// endpoint.
	BlockHashSignature bool `json:"block_hash_signature,omitempty"`
	// RestrictedMetadata is a map of restricted metadata keys and their
	// descriptions. This is used to indicate which metadata keys are
	// restricted and should not be used by clients.
	RestrictedMetadata map[string]string `json:"restricted_metadata,omitempty"`
}

// MarshalJSON overrides the default JSON marshaler to ensure nil slices
// are encoded as empty arrays instead of null. This improves cross-language
// compatibility, as some languages (e.g., JavaScript) may choke on null
// when expecting an array.
// See: https://github.com/coinbase/mesh-sdk-go/issues/62
func (a *Allow) MarshalJSON() ([]byte, error) {
	type Alias Allow
	
	// Ensure nil slices are converted to empty slices
	operationStatuses := a.OperationStatuses
	if operationStatuses == nil {
		operationStatuses = []*OperationStatus{}
	}
	
	operationTypes := a.OperationTypes
	if operationTypes == nil {
		operationTypes = []string{}
	}
	
	errors := a.Errors
	if errors == nil {
		errors = []*Error{}
	}
	
	callMethods := a.CallMethods
	if callMethods == nil {
		callMethods = []string{}
	}
	
	balanceExemptions := a.BalanceExemptions
	if balanceExemptions == nil {
		balanceExemptions = []*BalanceExemption{}
	}
	
	return json.Marshal(&struct {
		OperationStatuses []*OperationStatus `json:"operation_statuses"`
		OperationTypes    []string           `json:"operation_types"`
		Errors            []*Error           `json:"errors"`
		CallMethods       []string           `json:"call_methods,omitempty"`
		BalanceExemptions []*BalanceExemption `json:"balance_exemptions,omitempty"`
		*Alias
	}{
		OperationStatuses:   operationStatuses,
		OperationTypes:      operationTypes,
		Errors:              errors,
		CallMethods:         callMethods,
		BalanceExemptions:   balanceExemptions,
		Alias:               (*Alias)(a),
	})
}
