// Copyright 2020 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// ConstructionParseResponse ConstructionParseResponse contains an array of operations that occur in
// a transaction blob. This should match the array of operations provided to
// `/construction/preprocess` and `/construction/payloads`.
type ConstructionParseResponse struct {
	Operations []*Operation `json:"operations"`
	// All signers (addresses) of a particular transaction. If the transaction is unsigned, it
	// should be empty.
	Signers  []string               `json:"signers"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
