// Copyright 2025 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// ConstructionPreprocessOperationsRequest ConstructionPreprocessOperationsRequest is passed to the
// `/construction/preprocess_operations` endpoint so that a Rosetta implementation can parse
// high-level transaction construction operations into Rosetta operations. This endpoint allows
// the Rosetta API to handle operation parsing that might not be supported by the local
// OperationSelector. The request contains transaction construction data that should be parsed
// into a list of Rosetta operations.
type ConstructionPreprocessOperationsRequest struct {
	NetworkIdentifier *NetworkIdentifier     `json:"network_identifier"`
	FromAddress       string                 `json:"from_address,omitempty"`
	ConstructOp       string                 `json:"construct_op"`
	Options           map[string]interface{} `json:"options,omitempty"`
}