// Copyright 2025 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// ConstructionPreprocessOperationsResponse ConstructionPreprocessOperationsResponse contains the
// parsed operations and related information returned by the Rosetta implementation after processing
// the high-level transaction construction request. This response mirrors the return values of
// ParseTransactionConstructOp method to maintain compatibility.
type ConstructionPreprocessOperationsResponse struct {
	// The parsed operations that result from processing the construct_op.
	Operations []*Operation `json:"operations"`
	MaxFee     *Amount      `json:"max_fee,omitempty"`
	// Metadata as raw JSON bytes, matching ParseTransactionConstructOp return format for
	// compatibility with existing workflows.
	Metadata *string `json:"metadata,omitempty"`
}
