// Copyright 2020 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// ConstructionPreprocessResponse ConstructionPreprocessResponse contains the request that will be
// sent directly to `/construction/metadata`. If it is not necessary to make a request to
// `/construction/metadata`, options should be null.
type ConstructionPreprocessResponse struct {
	// The options that will be sent directly to `/construction/metadata` by the caller.
	Options map[string]interface{} `json:"options,omitempty" yaml:"options,omitempty"`
}
