// Copyright 2020 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package types

// SigningPayload SigningPayload is signed by the client with the keypair associated with an address
// using the specified SignatureType. SignatureType can be optionally populated if there is a
// restriction on the signature scheme that can be used to sign the payload.
type SigningPayload struct {
	// The network-specific address of the account that should sign the payload.
	Address       string        `json:"address"`
	HexBytes      string        `json:"hex_bytes"`
	SignatureType SignatureType `json:"signature_type,omitempty"`
}
