// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package reconciler

import (
	reconciler "github.com/coinbase/rosetta-sdk-go/reconciler"
	mock "github.com/stretchr/testify/mock"
)

// Option is an autogenerated mock type for the Option type
type Option struct {
	mock.Mock
}

// Execute provides a mock function with given fields: r
func (_m *Option) Execute(r *reconciler.Reconciler) {
	_m.Called(r)
}
