// Copyright 2023 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package server

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/coinbase/rosetta-sdk-go/asserter"
	"github.com/coinbase/rosetta-sdk-go/types"
)

// A EventsApiController binds http requests to an api service and writes the service results to the
// http response
type EventsApiController struct {
	service  EventsApiServicer
	asserter *asserter.Asserter
}

// NewEventsApiController creates a default api controller
func NewEventsApiController(
	s EventsApiServicer,
	asserter *asserter.Asserter,
) Router {
	return &EventsApiController{
		service:  s,
		asserter: asserter,
	}
}

// Routes returns all of the api route for the EventsApiController
func (c *EventsApiController) Routes() Routes {
	return Routes{
		{
			"EventsBlocks",
			strings.ToUpper("Post"),
			"/events/blocks",
			c.EventsBlocks,
		},
	}
}

// EventsBlocks - [INDEXER] Get a range of BlockEvents
func (c *EventsApiController) EventsBlocks(w http.ResponseWriter, r *http.Request) {
	eventsBlocksRequest := &types.EventsBlocksRequest{}
	if err := json.NewDecoder(r.Body).Decode(&eventsBlocksRequest); err != nil {
		EncodeJSONResponse(&types.Error{
			Message: err.Error(),
		}, http.StatusInternalServerError, w)

		return
	}

	// Assert that EventsBlocksRequest is correct
	if err := c.asserter.EventsBlocksRequest(eventsBlocksRequest); err != nil {
		EncodeJSONResponse(&types.Error{
			Message: err.Error(),
		}, http.StatusInternalServerError, w)

		return
	}

	result, serviceErr := c.service.EventsBlocks(r.Context(), eventsBlocksRequest)
	if serviceErr != nil {
		EncodeJSONResponse(serviceErr, http.StatusInternalServerError, w)

		return
	}

	EncodeJSONResponse(result, http.StatusOK, w)
}
