// Code generated by mockery. DO NOT EDIT.

package database

import (
	mock "github.com/stretchr/testify/mock"

	database "github.com/coinbase/rosetta-sdk-go/storage/database"
)

// BadgerOption is an autogenerated mock type for the BadgerOption type
type BadgerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: b
func (_m *BadgerOption) Execute(b *database.BadgerDatabase) {
	_m.Called(b)
}
