// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommitWorker is an autogenerated mock type for the CommitWorker type
type CommitWorker struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CommitWorker) Execute(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
