// Code generated by mockery v2.13.1. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommitWorker is an autogenerated mock type for the CommitWorker type
type CommitWorker struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CommitWorker) Execute(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCommitWorker interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommitWorker creates a new instance of CommitWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommitWorker(t mockConstructorTestingTNewCommitWorker) *CommitWorker {
	mock := &CommitWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
