// Code generated by mockery. DO NOT EDIT.

package syncer

import (
	mock "github.com/stretchr/testify/mock"

	syncer "github.com/coinbase/rosetta-sdk-go/syncer"
)

// Option is an autogenerated mock type for the Option type
type Option struct {
	mock.Mock
}

// Execute provides a mock function with given fields: s
func (_m *Option) Execute(s *syncer.Syncer) {
	_m.Called(s)
}
