// Copyright 2020 Coinbase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by: OpenAPI Generator (https://openapi-generator.tech)

package models

// Balance Balance is the array of Amount controlled by an AccountIdentifier. An underspecified
// AccountIdentifier may result in many amounts (ex: all ERC-20 balances for a single address).
type Balance struct {
	AccountIdentifier *AccountIdentifier `json:"account_identifier"`
	// A single account may have a balance in multiple currencies.
	Amounts []*Amount `json:"amounts"`
	// Account-based blockchains that utilize a nonce or sequence number should include that number
	// in the metadata. This number could be unique to the identifier or global across the account
	// address.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}
